DROP DATABASE IF EXISTS employee;

CREATE DATABASE employee;

USE employee;


CREATE TABLE employee(
id INTEGER PRIMARY KEY,
first_name VARCHAR(30) NOT NULL,
last_name VARCHAR(30) NOT NULL,
role_id INTEGER NOT NULL,
manager_id INTEGER NULL
);

CREATE TABLE manager(
id INTEGER PRIMARY KEY,
first_name VARCHAR(30) NOT NULL,
last_name VARCHAR(30) NOT NULL,
role_id INTEGER NOT NULL,
department_id INTEGER NOT NULL
);

CREATE TABLE role(
id INTEGER PRIMARY KEY,
title VARCHAR(30) NOT NULL,
salary DECIMAL NOT NULL,
department_id INTEGER
);

CREATE TABLE department (
id INT PRIMARY KEY,
name VARCHAR(30) NOT NULL
);
